### ISSUE TITLE
Share: iOS, gif and file not added to share

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GMEXT-MobileUtils#2]
When using the demo on iOS, attempting to use the share option for gif or file will not function and the associated file is not added to the share message.

Text, images, and PDFs all still work.

Android seems to also work correctly, at least for gifs

**Comment by jzavala-YYG** [comment]
Confirmed that the extension it's working, the issue it's that this feature doesn't work with some providers, that it's expected.
