### ISSUE TITLE
Implement Device Vibration Ext

### ISSUE THREAD

**Issue by Foxtrio** [YoYoGames/GMEXT-MobileUtils#4]
It would be nice to have access to device vibration optionality, as this is not present in native Game Maker.

**Comment by jzavala-YYG** [comment]
54a00f8d80c9fe040a4c591e35d3df23456421ab

**Comment by jzavala-YYG** [comment]
e96513b942f9f7497ee97e379b766bc856608071

**Comment by YYBartT** [comment]
The PR with the documentation for this has been merged and the wiki updated with the changes.
