### ISSUE TITLE
Implement Intent to Android App Settings

### ISSUE THREAD

**Issue by Foxtrio** [YoYoGames/GMEXT-MobileUtils#5]
If an OS permission is denied x times, Android disables you to request that permission again. In GML, calling os_request_permission would return **os_permission_denied_dont_request**.

The industry standard approach for this is to ask user to enable the permission through the Android's Settings.  Therefore, an extension to launch an intent to app settings would be good.

**Comment by jzavala-YYG** [comment]
iOS: 512eef65830a40f4d9d12e07f2cd730f85a8e586
Android: 0a0d80bbd0ca3d9cdff235dd33415a7193534c6b

**Comment by YYBartT** [comment]
Documented the new function `MobileUtils_AppPopupSettings_Show()`.
